### ISSUE TITLE
쥬스자판기 [STEP1] Jane, Harry

### ISSUE THREAD

**Issue by hemil0102** [jane1choi/ios-juice-maker#1]
## Feature Issue
쥬스자판기 STEP1 모델링 및 재고관리 기능 구현

## Todo
- [x] FruitStore 타입 정의(싱글톤)
    - 딸기, 바나나, 파인애플, 키위, 망고
    - 각 과일 초기 재고: 10개 
- [x] FruitStore 각 과일의 수량을 변경하는 기능
- [x] JuiceMaker 타입 정의 
- [x] JuiceMaker 쥬스 제조 기능 구현
