### ISSUE TITLE
쥬스자판기 [STEP2] Jane, Harry

### ISSUE THREAD

**Issue by hemil0102** [jane1choi/ios-juice-maker#2]
## Feature Issue
쥬스자판기 STEP2 재고관리 화면 오토 레이아아웃 및 기능 구현
화면 전환 구현
얼럿 구현

## Todo
- [x] 제조 화면에서 재고 관리 화면으로 네비 이동 구현
- [x] 재고 관리 화면 수량 변경 기능 구현 (스태퍼, 라벨)
- [x] 재고 관리 화면 Auto Layout
- [x] 쥬스 제조 후 얼럿 표시
- [x] 재고 부족시 얼럿 표시 및 기능 구현
