### ISSUE TITLE
쥬스자판기 [STEP3] Jane, Harry

### ISSUE THREAD

**Issue by hemil0102** [jane1choi/ios-juice-maker#4]
## Feature Issue
쥬스자판기 STEP3 기능 구현 
모달 및 오토레이아웃 구현

## Todo

- [x] 모달창 화면 제목 및 닫기 버튼 구현 
- [x] 화면 진입시 과일의 현재 재고 수량 표시
- [x] -, +를 통한 재고 수정
- [x] 다른 시뮬레이터 호환 오토레이아웃 적용
